services:
  api:
    container_name: movies-api
    build:
        context: .
        dockerfile: src/Movies.API/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://+:80
        - Imdb_BaseUrl=http://www.omdbapi.com/
        - Imdb_ApiKey=a38ffc7e
    ports:
        - 7001:80
  web:
    container_name: movies-web
    build:
        context: .
        dockerfile: src/Movies_Client/Dockerfile
    ports:
        - 4200:4200